
CREATE TABLE celebrity
(
  celebrity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(150) NOT NULL,
  category VARCHAR2(100) NOT NULL,
  management_fee NUMBER(10,2) CHECK (management_fee > 0),
  contract_start_date DATE NOT NULL,
  contract_end_date DATE NOT NULL,
  contact_details VARCHAR2(200) NOT NULL,
  CONSTRAINT ck_celebrity_dates CHECK (contract_end_date >= contract_start_date)
);

CREATE TABLE brand
(
  brand_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  brand_name VARCHAR2(120) NOT NULL,
  company_type VARCHAR2(100) NOT NULL,
  email VARCHAR2(150) NOT NULL UNIQUE,
  phone VARCHAR2(20) NOT NULL
);


CREATE TABLE booking
(
  booking_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  celebrity_id NUMBER NOT NULL,
  brand_id NUMBER NOT NULL,
  event_date DATE NOT NULL,
  event_type VARCHAR2(100) NOT NULL,
  event_location VARCHAR2(150) NOT NULL,
  booking_fee NUMBER(10,2) CHECK (booking_fee > 0),
  status VARCHAR2(50) CHECK (status IN ('Pending','Confirmed','Cancelled')),
  CONSTRAINT fk_booking_celebrity FOREIGN KEY (celebrity_id) REFERENCES celebrity(celebrity_id),
  CONSTRAINT fk_booking_brand FOREIGN KEY (brand_id) REFERENCES brand(brand_id)
);


CREATE TABLE payment
(
  payment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  booking_id NUMBER NOT NULL,
  payment_date DATE DEFAULT SYSDATE,
  amount_paid NUMBER(10,2) CHECK (amount_paid >= 0),
  payment_status VARCHAR2(50) CHECK (payment_status IN ('Paid','Pending')),
  CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES booking(booking_id)
);


CREATE TABLE awards
(
  award_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  celebrity_id NUMBER NOT NULL,
  award_name VARCHAR2(120) NOT NULL,
  award_year NUMBER(4) CHECK (award_year >= 1900),
  CONSTRAINT fk_awards_celebrity FOREIGN KEY (celebrity_id) REFERENCES celebrity(celebrity_id)
);


CREATE TABLE notifications
(
  notification_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  message VARCHAR2(255) NOT NULL,
  created_at DATE DEFAULT SYSDATE
);

